--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 06.04.2020 12:17:38
-- Server version: 5.5.5-10.3.13-MariaDB-log
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE schedule;

--
-- Drop table `tos_schedule`
--
DROP TABLE IF EXISTS tos_schedule;

--
-- Drop table `tos_classroom`
--
DROP TABLE IF EXISTS tos_classroom;

--
-- Drop table `tos_day`
--
DROP TABLE IF EXISTS tos_day;

--
-- Drop table `tos_lesson_num`
--
DROP TABLE IF EXISTS tos_lesson_num;

--
-- Drop table `tos_lesson_plan`
--
DROP TABLE IF EXISTS tos_lesson_plan;

--
-- Drop table `tos_student`
--
DROP TABLE IF EXISTS tos_student;

--
-- Drop table `tos_gruppa`
--
DROP TABLE IF EXISTS tos_gruppa;

--
-- Drop table `tos_special`
--
DROP TABLE IF EXISTS tos_special;

--
-- Drop table `tos_subject`
--
DROP TABLE IF EXISTS tos_subject;

--
-- Drop table `tos_teacher`
--
DROP TABLE IF EXISTS tos_teacher;

--
-- Drop table `tos_otdel`
--
DROP TABLE IF EXISTS tos_otdel;

--
-- Drop table `tos_user`
--
DROP TABLE IF EXISTS tos_user;

--
-- Drop table `tos_gender`
--
DROP TABLE IF EXISTS tos_gender;

--
-- Drop table `tos_role`
--
DROP TABLE IF EXISTS tos_role;

--
-- Set default database
--
USE schedule;

--
-- Create table `tos_role`
--
CREATE TABLE tos_role (
  role_id tinyint(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  sys_name varchar(255) NOT NULL,
  name varchar(50) NOT NULL,
  active tinyint(4) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (role_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `tos_gender`
--
CREATE TABLE tos_gender (
  gender_id tinyint(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  PRIMARY KEY (gender_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `tos_user`
--
CREATE TABLE tos_user (
  user_id bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  lastname varchar(255) NOT NULL,
  firstname varchar(255) NOT NULL,
  patronymic varchar(255) DEFAULT NULL,
  login varchar(255) DEFAULT NULL,
  pass varchar(255) DEFAULT NULL,
  gender_id tinyint(4) UNSIGNED NOT NULL,
  birthday date DEFAULT NULL,
  role_id tinyint(4) UNSIGNED NOT NULL,
  active tinyint(4) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE tos_user
ADD CONSTRAINT FK_tos_user_tos_gender_gender_id FOREIGN KEY (gender_id)
REFERENCES tos_gender (gender_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE tos_user
ADD CONSTRAINT FK_tos_user_tos_role_role_id FOREIGN KEY (role_id)
REFERENCES tos_role (role_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `tos_otdel`
--
CREATE TABLE tos_otdel (
  otdel_id smallint(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  active tinyint(4) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (otdel_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `tos_teacher`
--
CREATE TABLE tos_teacher (
  user_id bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  otdel_id smallint(6) UNSIGNED NOT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE tos_teacher
ADD CONSTRAINT FK_tos_teacher_tos_otdel_otdel_id FOREIGN KEY (otdel_id)
REFERENCES tos_otdel (otdel_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE tos_teacher
ADD CONSTRAINT FK_tos_teacher_tos_user_user_id FOREIGN KEY (user_id)
REFERENCES tos_user (user_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `tos_subject`
--
CREATE TABLE tos_subject (
  subject_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  otdel_id smallint(6) UNSIGNED NOT NULL,
  hours smallint(6) UNSIGNED NOT NULL,
  active tinyint(4) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (subject_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE tos_subject
ADD CONSTRAINT FK_tos_subject_tos_otdel_otdel_id FOREIGN KEY (otdel_id)
REFERENCES tos_otdel (otdel_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `tos_special`
--
CREATE TABLE tos_special (
  special_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  otdel_id smallint(6) UNSIGNED NOT NULL,
  active tinyint(4) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (special_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE tos_special
ADD CONSTRAINT FK_tos_special_tos_otdel_otdel_id FOREIGN KEY (otdel_id)
REFERENCES tos_otdel (otdel_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `tos_gruppa`
--
CREATE TABLE tos_gruppa (
  gruppa_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  special_id int(11) UNSIGNED NOT NULL,
  date_begin date NOT NULL,
  date_end date DEFAULT NULL,
  PRIMARY KEY (gruppa_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE tos_gruppa
ADD CONSTRAINT FK_tos_gruppa_tos_special_special_id FOREIGN KEY (special_id)
REFERENCES tos_special (special_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `tos_student`
--
CREATE TABLE tos_student (
  user_id bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  gruppa_id int(11) UNSIGNED NOT NULL,
  num_zach varchar(255) NOT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE tos_student
ADD CONSTRAINT FK_tos_student_tos_gruppa_gruppa_id FOREIGN KEY (gruppa_id)
REFERENCES tos_gruppa (gruppa_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE tos_student
ADD CONSTRAINT FK_tos_student_tos_user_user_id FOREIGN KEY (user_id)
REFERENCES tos_user (user_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `tos_lesson_plan`
--
CREATE TABLE tos_lesson_plan (
  lesson_plan_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  gruppa_id int(11) UNSIGNED NOT NULL,
  subject_id int(11) UNSIGNED NOT NULL,
  user_id bigint(20) UNSIGNED NOT NULL,
  PRIMARY KEY (lesson_plan_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE tos_lesson_plan
ADD CONSTRAINT FK_tos_lesson_plan_tos_gruppa_gruppa_id FOREIGN KEY (gruppa_id)
REFERENCES tos_gruppa (gruppa_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE tos_lesson_plan
ADD CONSTRAINT FK_tos_lesson_plan_tos_subject_subject_id FOREIGN KEY (subject_id)
REFERENCES tos_subject (subject_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE tos_lesson_plan
ADD CONSTRAINT FK_tos_lesson_plan_tos_teacher_user_id FOREIGN KEY (user_id)
REFERENCES tos_teacher (user_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `tos_lesson_num`
--
CREATE TABLE tos_lesson_num (
  lesson_num_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  time_lesson time NOT NULL,
  PRIMARY KEY (lesson_num_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `tos_day`
--
CREATE TABLE tos_day (
  day_id tinyint(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  PRIMARY KEY (day_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `tos_classroom`
--
CREATE TABLE tos_classroom (
  classroom_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  active tinyint(4) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (classroom_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `tos_schedule`
--
CREATE TABLE tos_schedule (
  schedule_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  lesson_plan_id int(11) UNSIGNED NOT NULL,
  day_id tinyint(4) UNSIGNED NOT NULL,
  lesson_num_id int(11) UNSIGNED NOT NULL,
  classroom_id int(11) UNSIGNED NOT NULL,
  PRIMARY KEY (schedule_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE tos_schedule
ADD CONSTRAINT FK_tos_schedule_tos_classroom_classroom_id FOREIGN KEY (classroom_id)
REFERENCES tos_classroom (classroom_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE tos_schedule
ADD CONSTRAINT FK_tos_schedule_tos_day_day_id FOREIGN KEY (day_id)
REFERENCES tos_day (day_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE tos_schedule
ADD CONSTRAINT FK_tos_schedule_tos_lesson_num_lesson_num_id FOREIGN KEY (lesson_num_id)
REFERENCES tos_lesson_num (lesson_num_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE tos_schedule
ADD CONSTRAINT FK_tos_schedule_tos_lesson_plan_lesson_plan_id FOREIGN KEY (lesson_plan_id)
REFERENCES tos_lesson_plan (lesson_plan_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table tos_role
--
INSERT INTO tos_role VALUES
(1, 'admin', 'Администратор', 1),
(3, 'manager', 'Менеджер', 1),
(4, 'teacher', 'Преподаватель', 1),
(5, 'student', 'Студент', 1);

-- 
-- Dumping data for table tos_gender
--
INSERT INTO tos_gender VALUES
(1, 'мужской'),
(2, 'женский');

-- 
-- Dumping data for table tos_user
--
-- Table schedule.tos_user does not contain any data (it is empty)

-- 
-- Dumping data for table tos_otdel
--
INSERT INTO tos_otdel VALUES
(1, 'Программирование', 1),
(2, 'Общеобразовательные дисциплины', 1),
(3, 'Строительство', 1);

-- 
-- Dumping data for table tos_special
--
INSERT INTO tos_special VALUES
(1, 'Информационные системы', 1, 1),
(2, 'Нефтегазовое дело', 2, 1),
(3, 'Строительство и эксплуатация', 3, 1),
(4, 'Электроснабжение', 3, 1),
(5, 'Вычислительная техника и', 1, 1);

-- 
-- Dumping data for table tos_teacher
--
-- Table schedule.tos_teacher does not contain any data (it is empty)

-- 
-- Dumping data for table tos_subject
--
-- Table schedule.tos_subject does not contain any data (it is empty)

-- 
-- Dumping data for table tos_gruppa
--
-- Table schedule.tos_gruppa does not contain any data (it is empty)

-- 
-- Dumping data for table tos_lesson_plan
--
-- Table schedule.tos_lesson_plan does not contain any data (it is empty)

-- 
-- Dumping data for table tos_lesson_num
--
INSERT INTO tos_lesson_num VALUES
(1, '1 пара', '08:30:00'),
(2, '2 пара', '10:10:00'),
(3, '3 пара', '12:20:00'),
(4, '4 пара', '14:00:00'),
(5, '5 пара', '15:40:00');

-- 
-- Dumping data for table tos_day
--
INSERT INTO tos_day VALUES
(1, 'Понедельник'),
(2, 'Вторник'),
(3, 'Среда'),
(4, 'Четверг'),
(5, 'Пятница'),
(6, 'Суббота');

-- 
-- Dumping data for table tos_classroom
--
-- Table schedule.tos_classroom does not contain any data (it is empty)

-- 
-- Dumping data for table tos_student
--
-- Table schedule.tos_student does not contain any data (it is empty)

-- 
-- Dumping data for table tos_schedule
--
-- Table schedule.tos_schedule does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;